class Tree:
    ...


class SyntaxTree(Tree):
    ...


class ParseTree(SyntaxTree):
    def getText(self) -> str: ...
    def getChild(self, i: int) -> ParseTree: ...
    def getParent(self) -> ParseTree: ...
    ...
