class Tree:
    """https://www.antlr.org/api/Java/org/antlr/v4/runtime/tree/Tree.html"""
    ...


class SyntaxTree(Tree):
    """https://www.antlr.org/api/Java/org/antlr/v4/runtime/tree/SyntaxTree.html"""
    ...


class ParseTree(SyntaxTree):
    """https://www.antlr.org/api/Java/org/antlr/v4/runtime/tree/ParseTree.html"""
    def getText(self) -> str: ...
    def getChild(self, i: int) -> ParseTree: ...
    def getParent(self) -> ParseTree: ...
    ...
